import Sidebar from "@/components/navigation/sidebar";
import Topbar from "@/components/navigation/topbar";
import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";

export const metadata: Metadata = {
    title: "File-Sharing",
    description: "Generated by Magang",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div className="flex flex-col h-screen">
            {/* Topbar positioned at the top */}
            <Topbar />
            {/* Main content area below topbar */}
            <div className="flex flex-1 overflow-hidden">
                <Sidebar />
                <main className="flex-1 bg-zinc-950 p-6 overflow-auto">
                    {children}
                </main>
            </div>
            <Toaster />
        </div>
    );
}
